title = "solution = problem |> cthree"
baseURL = "https://cthree.github.io/blog/"
languageCode = "en-us"
paginate = 5
publishDir = "docs"

theme = "after-dark"

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "cthree-1" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "â†©" # Provides a nicer footnote return link

[params]
description = "Topics in software development, system design, embedded devices and functional programming"
author = "Erik Petersen" # Optional, controls author name display on posts
hide_author = false # Optional, set true to hide author name on posts
show_menu = false # Optional, set true to enable section menu
powered_by = true # Optional, set false to disable credits
images = [] # Suggested, controls default OpenGraph images
theme_variant = "" # Optional, for use to overriding default theme

[params.seo.webmaster_verifications]
google = "" # Optional, Google verification code
bing = "" # Optional, Bing verification code
alexa = "" # Optional, Alexa verification code
yandex = "" # Optional, Yandex verification code
